events {
    worker_connections 1024;
}

http {
    upstream medpoint_api {
        server host.docker.internal:8001;
        server host.docker.internal:8002;
    }

    server {
        listen 80;

        location /health {
            return 200 "ok\n";
            add_header Content-Type text/plain;
        }

        location / {
            proxy_pass http://medpoint_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            add_header X-Upstream-Addr $upstream_addr;
        }
    }
}
